[program:admin-default]
process_name=%(program_name)s_%(process_num)02d
command=php artisan queue:work --sleep=3 --tries=3 --max-time=3600
directory=/data/www/admin
autostart=true
autorestart=true
numprocs=1
user=www-data
redirect_stderr=true

[program:admin-high-priority]
process_name=%(program_name)s_%(process_num)02d
command=php artisan queue:work --queue=high-priority --sleep=3 --tries=3 --max-time=3600
directory=/data/www/admin
autostart=true
autorestart=true
numprocs=1
user=www-data
redirect_stderr=true

[program:customer-default]
process_name=%(program_name)s_%(process_num)02d
command=php artisan queue:work --sleep=3 --tries=3 --max-time=3600
directory=/data/www/customer
autostart=true
autorestart=true
numprocs=1
user=www-data
redirect_stderr=true