[PHP]
;error_reporting = "E_ALL & ~E_DEPRECATED"
log_errors = "On"
default_charset = "UTF-8"
memory_limit = "128M"

[mail function]
mail.add_x_header = "Off"

[Session]
session.hash_function = "1"

[Date]
date.timezone = "Asia/Tokyo"

[mbstring]
mbstring.language = "Japanese"
; mbstring.internal_encoding = "UTF-8"
; mbstring.http_input = "pass"
; mbstring.http_output = "pass"
mbstring.encoding_translation = "off"
mbstring.detect_order = "UTF-8,SJIS,EUC-JP"
mbstring.substitute_character = "none"
